### ISSUE TITLE
How do I set it up?

### ISSUE THREAD

**Issue by AndreasHeintze** [animus-coop/vscode-phpstorm-formatter#12]
I installed this extension in VS Code. I use a Mac and it's not so clear how this should be setup to work.
I have a licensed PHPStorm installed, but what should I write in:
phpstormFormatter.ideBinPath: The full path to the PHPStorm <IDE_HOME>/bin directory.
phpstormFormatter.styleGuidePath: Format code according to this code style settings file.

In phpstormFormatter.ideBinPath I have written: /Applications/PhpStorm.app/Contents/bin
Is this correct and what should I write in phpstormFormatter.styleGuidePath ?

**Comment by soymanuvalle** [comment]
Hello @AndreasHeintze 

To be honest I didn't try this extension on a mac because I do not have one, it's something pending to do. However I use Linux and it works fine with the following config:
![image](https://user-images.githubusercontent.com/9582420/90251982-12d74a00-de15-11ea-8c2e-15857864c70a.png)
The `ideBinPath` is the location of the bin directory of your phpstorm installation. 
The `styleGuidePath` is the path of the style guide file you want to use for your formatting, this one is an optional field and you can avoid writing it if you desire to use the default phpstorm formatter settings.
